language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

matrix:
  fast_finish: true
  include:
  - go: 1.11.x

go_import_path: github.com/cbarraford/forge

script:
  - make lint
  - make test-cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
