language: go
sudo: false
go: stable

go_import_path: github.com/cbarraford/forge

before_install:
  - touch .env
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u gopkg.in/check.v1

script:
  - make lint-local
  - make test-cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
